version: '3.3'
services:
  node-1:
    image: com/emc/coprhd/sp:${VERSION}
    container_name: CoprHDSP-node-1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VERSION=${VERSION}
    ports:
      - 80:8080
      - 8080:8080
      - 5005:5005
    networks:
      internal-1:
        ipv4_address: 172.48.8.2
  mongo-1:
    image: mongo:3.6
    container_name: mongo-node-1
    ports:
      - 27017:27017
    networks:
      internal-1:
        ipv4_address: 172.48.8.3
  hz-1:
    image: com/emc/coprhd/sp/hz:3.9.3
    container_name: hz-node-1
    ports:
      - 5701:5701
    build:
      context: hz-config
      dockerfile: Dockerfile
      args:
        - NODE=1
    networks:
      internal-1:
        ipv4_address: 172.48.8.4

networks:
  internal-1:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.48.8.0/24

        qt=/all&q=ceiling+fan&facet.field={!key%3D\"Get+It+Fast\"}ATTR_GetItFast&facet.field={!key%3D\"Get+It+Fast+2+day\"}ATTR_Delivery&facet.field={!key%3D\"Brand\"}ATTR_Brand&facet.field={!key%3D\"Price\"}ATTR_Price&facet.field={!key%3D\"Special+Values\"}ATTR_SpecialValues&facet.field={!key%3D\"How+To+Get+It\"}ATTR_HowToGetIt&facet.field={!key%3D\"ENERGY+STAR+CERTIFIED\"}ATTR_ENERGYSTARCERTIFIED&facet.field={!key%3D\"New+Arrival\"}ATTR_NewArrival&facet.field={!key%3D\"Review+Rating\"}ATTR_ReviewRating&facet.field={!key%3D\"Category\"}categoryLevels&facet=true&facet.mincount=1&f.ATTR_Delivery.facet.prefix=121_&f.ATTR_Brand.facet.sort=count&f.ATTR_Brand.facet.limit=225&f.categoryLevels.facet.prefix=1-&fl=id,ATTR_Category,parentId,INS_121&lemmaQuery=ceiling+fan&rows=24&start=0&fq=-isDiscontinued:true&fq=-isHidden:true&fq=(purchaseType:Instore+AND+storestatus_121:(100+OR+200+OR+300+OR+400))+OR+storestatus_8119:(100)&fq=purchaseType:Online&json.facet={nGroups:+'unique(parentId)'}&omitHeader=true&spellcheck=false&storeId=121&productType=ceiling+fan&elevateIds=300930186,206775554,301919991,204857192,301136111,205547378,300654436,301986855,203382587,300662511,300787132,206123281,300787130,301009049,300593306,300593308,203244867,300937624,301756341,205718223,206394978,301986862,301160203,206925000