version: '3.3'
services:
  node-1:
    image: com/emc/coprhd/sp:${VERSION}
    container_name: CoprHDSP-node-1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VERSION=${VERSION}
    ports:
      - 80:8080
      - 8080:8080
      - 5005:5005
    networks:
      internal-1:
        ipv4_address: 172.48.8.2
  mongo-1:
    image: mongo:3.6
    container_name: mongo-node-1
    ports:
      - 27017:27017
    networks:
      internal-1:
        ipv4_address: 172.48.8.3
  hz-1:
    image: com/emc/coprhd/sp/hz:3.9.3
    container_name: hz-node-1
    ports:
      - 5701:5701
    build:
      context: hz-config
      dockerfile: Dockerfile
      args:
        - NODE=1
    networks:
      internal-1:
        ipv4_address: 172.48.8.4
  sizer-1:
    image: com/emc/vnxsizer-api:latest
    container_name: sizer-1
    ports:
      - 8081:8080
    networks:
      internal-1:
        ipv4_address: 172.48.8.5
  srm-1:
    image: com/emc/coprhd/srm:${VERSION}
    container_name: srm-1
    ports:
      - 8082:8080
    networks:
      internal-1:
        ipv4_address: 172.48.8.6

networks:
  internal-1:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.48.8.0/24