banner:
  charset: UTF-8
  location: file:config/banner.txt
server:
  tomcat.uri-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
logging:
  config: config/log4j2.yml
spring:
  data:
    mongodb:
      database: admin
      host: localhost
      username: coprhd
      password: password
      port: 27017
      repositories:
        type: auto
com:
  emc:
    coprhd:
      sp:
        mongo:
          vp-collection-name: virtual-pools