banner:
  charset: UTF-8
  location: file:config/banner.txt
server:
  tomcat.uri-encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
logging:
  config: config/log4j2.yml
spring:
  data:
    mongodb:
      database: admin
      host: localhost
      username: coprhd
      password: password
      port: 27017
      repositories:
        type: auto
  jade4j:
    caching: false
    checkTemplateLocation: true
    contentType: text/html
    encoding: UTF-8
    mode: HTML
    prefix: file:templates/
    prettyPrint: false
    suffix: .jade
  resources:
    static-locations: file:static/
hazelcast:
  client:
    config: config/hazelcast-client.xml
com:
  emc:
    coprhd:
      sp:
        mongo:
          vp-collection-name: virtual-pools
        vnx:
          sizer:
            template: resources/vnxsizer/template.json
        vipr:
          host: 127.0.0.1
          login: admin
          password: password
          timeout: 2000
          stub:
            storage-system: resources/stub/storage-system.json
            storage-pools: resources/stub/storage-pools.json
            virtual-pools: resources/stub/virtual-pools.json
