Configutation:
  name: local

  Properties:
    Property:
      name: log-path
      value: "logs"

  Appenders:
    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{36} - %replace{%msg}{\\R}{}%n"

#    RollingFile:
#      name: RollingFile_Appender
#      fileName: "${log-path}/app.log"
#      filePattern: "${log-path}/archive/app.log.%d{yyyy-MM-dd-hh-mm}.gz"
#      PatternLayout:
#        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{36} - %msg%n"
#      Policies:
#        SizeBaseFdTriggeringPolicy:
#          size: 3 MB
#      DefaultRollOverStrategy:
#        max: 30

  Loggers:
    Logger:
      - name: org.jboss
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: org.apache
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: org.springframework
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: org.eclipse
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: org.mongodb
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: sun.rmi
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
      - name: javax.activation
        additivity: false
        level: warn
        AppenderRef:
          - ref: Console_Appender
            level: warn
#          - ref: RollingFile_Appender
#            level: warn
    Root:
      level: debug
      additivity: false
      AppenderRef:
#        - ref: RollingFile_Appender
        - ref: Console_Appender