Configutation:
  name: default

  Properties:
    Property:
      name: log-path
      value: "logs"

  Appenders:

    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{36} - %msg%n"

    RollingFile:
      name: RollingFile_Appender
      fileName: logs/CoprHDSM.log
      filePattern: "logs/archive/CoprHDSM.log.%d{yyyy-MM-dd-hh-mm}.gz"
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] %logger{36} - %msg%n"
      Policies:
        SizeBasedTriggeringPolicy:
          size: 5 MB
      DefaultRollOverStrategy:
        max: 30

  Loggers:
      Logger:
        - name: org.hibernate
          additivity: false
          level: off
        - name: org.jboss
          additivity: false
          level: off
        - name: org.apache
          additivity: false
          level: off
        - name: com.emc.vipr.client
          additivity: false
          level: info
          AppenderRef:
            - ref: Console_Appender
              level: off
            - ref: RollingFile_Appender
              level: info
        - name: org.eclipse
          additivity: false
          level: off
        - name: org.mongodb
          additivity: false
          level: off
        - name: sun.rmi
          additivity: false
          level: off
        - name: javax.activation
          additivity: false
          level: off
        - name: org.springframework
          additivity: false
          level: warn
          AppenderRef:
            - ref: Console_Appender
              level: warn
            - ref: RollingFile_Appender
              level: warn
      Root:
        level: debug
        additivity: false
        AppenderRef:
          - ref: RollingFile_Appender
          - ref: Console_Appender